default_parameters = {
    'DEFAULT_IP_ADDRESS': '127.0.0.8',
    'DEFAULT_PORT': 8888,
    'MAX_CONNECTIONS': 8,
    'MAX_PACKAGE_LENGTH': 4096,
    'ENCODING': 'utf-8',
    'ACTION': 'action',
    'TIME': 'time',
    'USER': 'user',
    'ACCOUNT_NAME': 'account_name',
    'PRESENCE': 'presence',
    'RESPONSE': 'response',
    'ERROR': 'error',
    'START_RANGE_PORT': 1024,
    'END_RANGE_PORT': 65535,
}
